/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SubmissionInput"];
                };
            };
            responses: {
                /** @description 제출 개시 — presigned 업로드 URL 발급 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionCreated"];
                    };
                };
                /** @description 유효하지 않은 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Turnstile/오리진 거부 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description rate limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FinalizeInput"];
                };
            };
            responses: {
                /** @description 확정 — D1 레코드 적재 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinalizeResult"];
                    };
                };
                /** @description 검증 실패(업로드 누락/타입/크기) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 토큰 불일치 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 제출 없음/만료 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    election?: string;
                    status?: "unverified" | "reviewing" | "confirmed" | "disputed" | "debunked" | "corrected";
                    sido?: string;
                    sigungu?: string;
                    tag?: string;
                    from?: string;
                    to?: string;
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 제보 목록(pending 제외) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportList"];
                    };
                };
                /** @description 유효하지 않은 쿼리 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 제보 상세 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Report"];
                    };
                };
                /** @description 없음(또는 pending) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SubmissionCreated: {
            submission_id: string;
            finalize_token: string;
            uploads: {
                staging_key: string;
                put_url: string;
            }[];
        };
        Error: {
            error: string;
        };
        Region: {
            sido?: string;
            sigungu?: string;
            eup_myeon_dong?: string;
        };
        Source: {
            /** Format: uri */
            url?: string;
            text?: string;
            type?: string;
            captured_at?: string;
            /** Format: uri */
            archive_url?: string;
        };
        AttachmentInput: {
            filename: string;
            /** @enum {string} */
            mime: "image/jpeg" | "image/png" | "image/gif" | "image/webp";
            size: number;
            sha256?: string;
        };
        SubmissionInput: {
            election: string;
            title: string;
            summary?: string;
            body?: string;
            region?: components["schemas"]["Region"];
            occurred_at?: string;
            tags?: string[];
            sources?: components["schemas"]["Source"][];
            attachments?: components["schemas"]["AttachmentInput"][];
            exif?: unknown[];
            consent?: boolean;
            turnstile_token: string;
        };
        Attachment: {
            filename: string;
            r2_key: string;
            sha256: string;
            mime: string;
            size: number;
        };
        FinalizeResult: {
            report_id: string;
            attachments: components["schemas"]["Attachment"][];
        };
        FinalizeInput: {
            finalize_token: string;
        };
        ReportSummary: {
            id: string;
            status: string;
            election: string;
            title: string;
            summary: string | null;
            region: components["schemas"]["Region"];
            occurred_at: string | null;
            collected_at: string;
            tags: string[];
            attachment_count: number;
        };
        ReportList: {
            items: components["schemas"]["ReportSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        Verification: {
            reviewer: string | null;
            method: string | null;
            reviewed_at: string | null;
            notes: string | null;
            evidence_links: string[] | null;
        };
        Report: {
            id: string;
            status: string;
            election: string;
            title: string;
            summary: string | null;
            body: string | null;
            region: components["schemas"]["Region"];
            occurred_at: string | null;
            collected_at: string;
            tags: string[];
            sources: components["schemas"]["Source"][];
            attachments: components["schemas"]["Attachment"][];
            rebuttals: {
                text: string;
                source_url?: string;
            }[] | null;
            related: string[] | null;
            consent: boolean | null;
            license: string;
            verification: components["schemas"]["Verification"];
            created_at: string;
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
